name: tekvando
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  percent_indicator: ^4.2.3
  #story
  story_view: ^0.16.5
  #grapic
  syncfusion_flutter_gauges: ^27.1.58
  #set managment
  provider: ^6.1.2
  #cache
  shared_preferences: ^2.3.2
  hive_flutter:
  #language
  easy_localization: ^3.0.7
  #router
  auto_route: ^9.2.2
  #network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  http: ^1.2.2
  #model parse
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  #core eştlik kontrol
  equatable: ^2.0.5
  #network control
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  #image
  image_picker: ^1.1.2
  image_stack: ^2.1.1
  cached_network_image: ^3.4.1
  #file
  file_picker: ^8.1.2
  #permission
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  #swiper
  flutter_card_swiper: ^7.0.1
  #qr
  qr_code_scanner: ^1.0.1
  pretty_qr_code: ^3.3.0
  #chat ui
  flutter_chat_ui: ^1.6.15
  open_filex: ^4.5.0
  flutter_link_previewer: ^3.2.2 #link preview
  bubble: ^1.2.1 # chat ui bubble
  #dropdown
  dropdown_button2: ^2.3.9
  #share
  share_plus: ^10.0.2
  #socket
  web_socket_channel: ^3.0.1
  #location
  geolocator: ^13.0.1
  #
  get_it: ^8.0.0
  #onesignal
  onesignal_flutter: ^5.2.5
  # firebase
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner:
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0
  change_app_package_name: ^1.4.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/setting/

  fonts:
    - family: Akasi
      fonts:
        - asset: assets/fonts/akashi.ttf
